samples:
    table_for_reads.csv

kallisto_idx:
    kallisto/transcripts.idx

transcripts:
    data/ref/transcriptome.chr21.fa

transcripts_gtf:
    data/ref/annotation.chr21.gtf

clust_dist:
    clustering_distance.txt
